Feature/126 watchlist controllers
esentis/ieemdb-adopse-2021 pull request #127
Opened 2021-05-08 23:29 UTC by vagmark30

Closes #126
Missing remove list, remove from list

2021-05-08 23:32 UTC, esentis commented on src/Ieemdb.Web/Controllers/WatchlistController.cs
> +      return Ok(watchlists);
Πρέπει να επιστρέψουμε Dto όχι το Entity.  Ξέχασες το mapping :P

2021-05-08 23:33 UTC, esentis commented on src/Ieemdb.Web/Controllers/WatchlistController.cs
> +  [Route("api/movie")]
Θα είναι σε ξεχωριστό endpoint, api/watchlist

2021-05-08 23:34 UTC, esentis commented on src/Ieemdb.Web/Controllers/WatchlistController.cs
> +    [HttpGet("usersLists")]
Μιας και θα ειναι ξεχωριστό endpoint αυτό θα είναι απλα 
```csharp
[HttpGet("")]
```

2021-05-08 23:35 UTC, esentis commented on src/Ieemdb.Web/Controllers/WatchlistController.cs
> +    [HttpGet("list")]
```csharp
[HttpGet("{id}")]
```

2021-05-08 23:36 UTC, esentis commented on src/Ieemdb.Web/Controllers/WatchlistController.cs
> +    public async Task<ActionResult<List<MovieWatchlist>>> GetWatchlist(long watchlistId, CancellationToken token = default)
```csharp
long id
```

2021-05-08 23:36 UTC, esentis commented on src/Ieemdb.Web/Controllers/WatchlistController.cs
> +    [HttpPost("addMovieToWatchlist")]
[HttpPost("")]

2021-05-08 23:39 UTC, esentis commented on src/Ieemdb.Web/Controllers/WatchlistController.cs
> +    [HttpPost("addWatchlist")]
```csharp
[HttpGet("")]
```

2021-05-08 23:41 UTC, esentis requested changes
Πέρα απο τα comment λείπουν και τα migrations ! Εβαλες Watchlist στο DbContext αλλα δεν εβαλες το migration του.

2021-05-09 22:09 UTC, esentis commented on src/Ieemdb.Web/Controllers/WatchlistController.cs
>      /// <response code="200">Returns results. </response>
Κάτω απο τα response code μπαίνει το <returns></returns>.

2021-05-09 22:18 UTC, esentis commented on src/Ieemdb.Web/Helpers/MappingConfiguration.cs
> +      .Map<WatchlistDto, Watchlist>(mapper => watchlistDto => new Watchlist() { Name = watchlistDto.Name, Id = watchlistDto.WatchlistId });
??

2021-05-09 22:19 UTC, esentis requested changes
Χρειάζεται κιάλλες αλλαγές ! Πριν το στείλεις τρέξτο τοπικά και δοκίμασε το.

2021-05-09 22:23 UTC, esentis commented on src/Ieemdb.Web/Helpers/MappingConfiguration.cs
> +      .Map<WatchlistDto, Watchlist>(mapper => watchlistDto => new Watchlist() { Name = watchlistDto.Name, Id = watchlistDto.WatchlistId });
Τι ακριβώς κάνεις mapping ? Το WatchlistDto δεν εχει καν πεδίο name.

2021-05-09 22:25 UTC, esentis requested changes
Κοίτα καλύτερα το mapping. Δες πως έχει υλοποιηθεί το favorite, παρόμοια ειναι άλλωστε.

2021-05-10 07:17 UTC, esentis commented on src/Ieemdb.Persistence/IeemdbDbContext.cs
> +
```
src/Ieemdb.Persistence/IeemdbDbContext.cs(44,18): Error CS0246: The type or namespace name 'MovieWatchlist' could not be found (are you missing a using directive or an assembly reference?)
```
Υπάρχει το 
```csharp
public DbSet<MovieWatchlist> MovieWatchlists { get; set; }
```
Το οποίο πρέπει να φύγει !

2021-05-10 07:19 UTC, esentis requested changes
Καθάρισε λιγο το DbContext, την αλλη φορά θα ζητήσω και screenshot απο success response απο τους controllers !

2021-05-10 07:42 UTC, vagmark30 commented on src/Ieemdb.Persistence/IeemdbDbContext.cs
> +
δεν υπαρχει αυτη η γραμμη σε μενα. στο τελευταιο commit την εβγαλα
![image](https://user-images.githubusercontent.com/44836858/117623345-567c9b80-b17c-11eb-85d5-3ba6a432085e.png)

2021-05-10 07:47 UTC, vagmark30 commented
> Καθάρισε λιγο το DbContext, την αλλη φορά θα ζητήσω και screenshot απο success response απο τους controllers !

Ολοι οι watchlist controllers ετρεξαν

2021-05-10 07:47 UTC, esentis approved these changes

2021-05-10 07:48 UTC, merged