Initial Commit
esentis/ieemdb-adopse-2021 pull request #21
Opened 2021-03-23 15:28 UTC by TeoMastro

Closes #3 
# Pull Request Template

Clean up this template and provide relevant information about your pull request!

## All Submissions

* [ ] Have you followed the guidelines in our [Contributing](../.github/CONTRIBUTING.md) document?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [ ] Does your pull request target an open issue?

### New Feature Submissions

* [ ] Does your submission pass tests?
* [ ] Have you lint your code locally prior to submission?

### Changes to Core Features

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

2021-03-23 15:43 UTC, esentis requested changes
Δεν δουλεύει πια το user authorization/authentication με τα components που αφαίρεσες

2021-03-23 15:43 UTC, esentis commented on src/Ieemdb.Web/ClientApp/src/App.js
> -import { ApplicationPaths } from './components/api-authorization/ApiAuthorizationConstants';
Authorization components are required for user validation

2021-03-23 15:43 UTC, esentis commented on src/Ieemdb.Web/ClientApp/src/App.js
> -        <Route path={ApplicationPaths.ApiAuthorizationPrefix} component={ApiAuthorizationRoutes} />
Authorization components are required for user validation

2021-03-23 15:45 UTC, esentis commented
Διαβάζουμε το description που συμπληρώνουμε 🙏

2021-03-23 22:00 UTC, esentis approved these changes
Seems ok !

2021-03-24 16:47 UTC, KostisGrf reviewed
Seems ok

2021-03-24 22:34 UTC, GavriilJim approved these changes
Seems ok

2021-03-24 22:35 UTC, esentis approved these changes

2021-03-24 22:42 UTC, KostisGrf approved these changes

2021-03-26 19:13 UTC, merged