Adds Movie Dataset
esentis/ieemdb-adopse-2021 pull request #31
Opened 2021-03-29 20:44 UTC by KostisGrf

#30

2021-03-29 20:51 UTC, esentis commented on src/Ieemdb.Web/ClientApp/src/components/Movie_Dataset.js
> +    "genres":["Action","Comedy","Fantasy"]},
Θα μπορούσε να έχει και directors/writers/duration/countryOrigin για να ειναι το ιδιο με το δικο μας μοντέλο.

2021-03-29 20:52 UTC, esentis requested changes
Μερικές μικρές αλλαγές.

2021-03-29 22:21 UTC, esentis approved these changes
LGTM !

2021-03-30 08:48 UTC, vagmark30 approved these changes
Seems legit

2021-03-30 12:46 UTC, TeoMastro approved these changes
seems legit to me mate

2021-03-30 17:49 UTC, merged