Change css style throughout the app
esentis/ieemdb-adopse-2021 pull request #78
Opened 2021-04-18 22:43 UTC by GavriilJim

Closes #65

2021-04-18 23:04 UTC, esentis requested changes
![image](https://user-images.githubusercontent.com/52862600/115163760-8d96ea00-a0b3-11eb-8d60-fa25e5ff95d4.png)

2021-04-18 23:24 UTC, KostisGrf submitted a review, later dismissed

2021-04-19 07:13 UTC, esentis approved these changes

2021-04-19 09:12 UTC, TeoMastro approved these changes
in mhtsos we trust!

2021-04-19 12:50 UTC, KostisGrf approved these changes

2021-04-19 12:58 UTC, merged