Refactored Names on every Individual instance
esentis/ieemdb-adopse-2021 pull request #79
Opened 2021-04-18 23:09 UTC by vagmark30

Closes #69 
Checked post and put methods on Swagger

2021-04-19 07:22 UTC, esentis commented on src/Ieemdb.Persistence/Models/Actor.cs
>          NormalizedSearch = value.NormalizeSearch();
Το NormalizedSearch πριν ήταν μόνο για το FirstName, τώρα που βάζουμε και LastName κανεις normalize και αλλαζεις την ιδια μεταβλητη. Τωρα αναγκαστικά θα έχουμε δύο NormalizedSearch, NormalizedFirstName και NormalizedLastName. Αυτό ισχύει σε όλα τα μοντέλα που έχει το NormalizedSearch.

2021-04-19 07:24 UTC, esentis requested changes
Δές το comment που έβαλα ;)

2021-04-19 11:37 UTC, vagmark30 commented
Work is required to files IeemdbDbContext.cs  DbContextExtensions.cs for the ability to search function.

2021-04-19 11:51 UTC, esentis commented on src/Ieemdb.Persistence/IeemdbDbContext.cs
>        builder.Entity<MovieActor>(e =>
Πρέπει να φύγουν αυτά, το NormalizedLastNameSearch / NormalizedFirstNameSearch δεν πρέπει να είναι index της βασης. Το NormalizeSearch πρεπει να μείνει γιατι είναι για το Full Text Search. 
Π.χ 
```csharp
 builder.Entity<Actor>()
        .HasIndex(e => e.NormalizedSearch)
        .IsTsVectorExpressionIndex("english");

2021-04-19 11:55 UTC, esentis commented on src/Ieemdb.Persistence/Abstractions/ISearchableNames.cs
> +}
Δεν υπάρχει λόγος να το κάνεις interface, ας ειναι πεδία μεσα στο Model.

2021-04-19 11:59 UTC, esentis requested changes
Αν δείς το DbContext extension το οποιο κάνει στην ουσία το Full Text Search του λεω να κοιτάξει το NormalizedSearch πεδίο του Entity που ψάχνω.
 ```csharp
 public static class DbContextExtensions
  {
    public static IQueryable<TEntity> FullTextSearch<TEntity>(this IQueryable<TEntity> source, string query)
      where TEntity : ISearchable
      => source
        .Where(x => EF.Functions.ToTsVector("english", x.NormalizedSearch).Matches(query));
  }
  ```
  
  Επειδή Full Text Search γίνεται σε φυσική γλώσσα, το normalizedSearch στους Actors/Writers/Directors είναι το Bio τους (δηλαδή θα κάνει ότι έκανες με το άλλο πεδίο απλά θα ειναι το Bio που πρέπει να περασει normalization), και στις ταινίες θα είναι ο τίτλος και γιατι όχι η πλοκή.

2021-04-20 07:27 UTC, esentis approved these changes
Νομίζω πως είμαστε καλα για τωρα :P

2021-04-20 07:28 UTC, merged